In [6]:
import numpy as np
matrix = np.array([[0.75,0.02,0.1], [0.2,0.9,0.2], [0.05,0.08,0.7]])
matrix_100 = np.array([[75,2,10], [20,90,20], [5,8,70]])

In [7]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

eigenvalues, eigenvectors = np.linalg.eig(matrix_100)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
print(eigenvectors)



Eigenvalues: [1.   0.7  0.65]
Eigenvectors:
[[-1.88144174e-01 -8.08122036e-01 -7.07106781e-01]
 [-9.40720868e-01  5.05076272e-01  2.05361068e-15]
 [-2.82216261e-01  3.03045763e-01  7.07106781e-01]]
Eigenvalues: [100.  70.  65.]
Eigenvectors:
[[-1.88144174e-01 -8.08122036e-01 -7.07106781e-01]
 [-9.40720868e-01  5.05076272e-01  3.73941050e-15]
 [-2.82216261e-01  3.03045763e-01  7.07106781e-01]]


In [2]:
# Calculate the determinant
determinant = np.linalg.det(matrix)

# Print the determinant
print("Determinant of the matrix is:", determinant)

Determinant of the matrix is: 0.455


In [17]:
import numpy as np
#Solving a system of linear equations: find a linear combination of eigenvectors which is equal to the economic condition at time=0

#A= eigenvectors
v=np.array([[0.2,-1.6,1],[1,1,0],[0.3,0.6,-1]])
print(v)
#b
year_0=np.array([0,0,1])
print(year_0)
#solve
X=np.linalg.solve(v,year_0)
print(X)
#verify solution
result=np.dot(v,X)
print(result)

[[ 0.2 -1.6  1. ]
 [ 1.   1.   0. ]
 [ 0.3  0.6 -1. ]]
[0 0 1]
[ 0.66666667 -0.66666667 -1.2       ]
[0. 0. 1.]


In [51]:
def forecast(time):
    #define year
    year=time
    # construct dynamic system
    a=X[0]
    b=X[1]
    c=X[2]
    #define eigenvalues
    eig1=1
    eig2=0.7
    eig3=0.65
    #define eigenvector matrix
    v=np.array([[0.2,-1.6,1],[1,1,0],[0.3,0.6,-1]])
    #multiply a,b,c with respective eigenvalues to the power (**) of the year
    vector=np.array([a*eig1**year,b*eig2**year,c*eig3**year])
    #print(vector)
    #calculate economic condition
    economy=np.dot(v,vector)
    #print results
    print(f"boom: {economy[0]}\nnormal: {economy[1]}\nrecession: {economy[2]}")




In [55]:
forecast(2)

boom: 0.1489999999999999
normal: 0.34
recession: 0.511
